### ISSUE TITLE
Implement prepopulation

### ISSUE THREAD

**Issue by jrvidal** [brodysoft/Cordova-SQLitePlugin#10]
There is plenty of "third-party" code for copying a pre-populated database instead of creating a new one.

I have started a [fork](http://github.com/jrvidal/Cordova-SQLitePlugin) to try to get this feature working consistently in both Android and iOS. The Android part is already done by @jarlehansen.

Anyway, feedback welcome.

**Comment by brodybits** [comment]
Moving discussion to #172.

**Comment by brodybits** [comment]
I have now pushed a new release to master with optional support for pre-populated database. Please see README.md for details.

**Comment by StevensCol** [comment]
I have an issue with the plugin in the next scene:

- I download the pre-populated db when the user login successfully on my app.
- I storage the db on the cordova.file.dataDirectory path (in this point, this works fine, the db is located on this directory successfully).
- Whe i use:

`...
var dbPath = cordova.file.dataDirectory + dbName;
var db = window.sqlitePlugin.openDatabase(dbPath);

db.transaction(function(tx){

tx.executeSql("some query", [], function(tx, data){
//do-something
}, function(err){
console.log(JSON.stringify(err));
});
});`

Next, the program enter on function error, and prints the next object error:

![simulator screen shot 12 02 2016 12 18 39 p m](https://cloud.githubusercontent.com/assets/7546162/13014724/44cba8c4-d183-11e5-87dc-17b220fc36b6.png)

I dont know if this plugin works fine with pre-populated databases, or the error message on execute the sql statment is for some permissions on iOS. :s
