### ISSUE TITLE
executeSql parameter as array, iOS

### ISSUE THREAD

**Issue by matb33** [brodysoft/Cordova-SQLitePlugin#144]
If you pass a parameter that is actually an array, the WebSQL implementation will automatically typecast it as a string. However, at least for the iOS implementation of your plugin, this results in an error.

Example:
`executeSql("INSERT ... (?, ?)", ['abc', [1,2,3]]);`
In WebSQL, the above would be accepted and typecast to resemble the equivalent of:
`executeSql("INSERT ... (?, ?)", ['abc', '1,2,3']);`

Should be a simple fix in your JS to toString parameters that are arrays.

Apologies for the lack of a repro scenario.

**Comment by brodybits** [comment]
This issue is now reproduced for all three platforms Android/iOS/WP(8). For Android and iOS the data is stored incorrectly. For WP(8) the executeSql fails silently, returning no result or error callbacks.

**Comment by brodybits** [comment]
The fix has been validated on Android/iOS/WP(8) and published.
