### ISSUE TITLE
Database not closing on Android

### ISSUE THREAD

**Issue by magikozio** [brodysoft/Cordova-SQLitePlugin#150]
I was experiencing a problem on Android platform, when closing the database. This caused problems in my app, since in some cases I needed to reload the page, and to prevent opening the same database multiple times, before the reload I was closing the DB. Unfortunately this seemed not to work and in logcat I had:

```
sqlite returned: error code = 5, msg = database is locked, db=/data/data/[APP-ID]/databases/webview_db
sqlite returned: error code = 5, msg = database is locked, db=/data/data/[APP-ID]/databases/webview_db
CREATE TABLE android_metadata failed
Failed to open the database. closing it.
android.database.sqlite.SQLiteDatabaseLockedException: database is locked
... and so on ...
```

The issue seemed to be in the run() method of DBRunner:

```
dbrmap.remove(dbname); // (should) remove ourself

closeDatabaseNow(dbname);
```

Here, first the mapping with the db name is removed and then the database connection closed. But the closeDatabaseNow method uses that mapping to retrieve the database object, and since it has been removed, nothing is returned and the database is not closed.

The solution was simple: I just switched those rows and the database was closed correctly.

I hope this can help someone

**Comment by brodybits** [comment]
The fix has been published.

**Comment by durgaprasadp** [comment]
Hi Friends, 

 Please help me i am new to cordova application development and i got below exception while login or access application multiple times please help me,Thanks in Advance 

06-01 18:19:53.533: E/SQLitePlugin(16127): unexpected error, stopping db thread
06-01 18:19:53.533: E/SQLitePlugin(16127): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1113)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:824)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:510)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:484)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:383)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:232)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:889)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:859)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:711)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:704)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at org.pgsqlite.SQLitePlugin.openDatabase(SQLitePlugin.java:241)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at org.pgsqlite.SQLitePlugin.access$0(SQLitePlugin.java:223)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:836)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-01 18:19:53.533: E/SQLitePlugin(16127): 	at java.lang.Thread.run(Thread.java:841)
06-01 18:19:56.133: E/ViewRootImpl(16127): sendUserActionEvent() mView == null

**Comment by brody2consult** [comment]
@durgaprasadp I am very sorry but this is not enough information to help you and from the log, I can see that you are using an old version of the plugin. Also, this issue was regarding a small fix that was needed in the past. The fix has been applied and this issue is now closed.

Please upgrade to use the latest version of this plugin. If you are still having problems, please do the following:
- Please make sure you are using the latest version. Older versions are normally not supported.
- Isolate the smallest test program that you can make to reproduce your problem
- Raise a new issue and post the _entire_ test program where you see the issue.

**Comment by durgaprasadp** [comment]
Hi Brodybits,

Thanks for replay i updated new Sqlite plugin but in that alter command not working. I am using below code for adding new column to existing table


dbObj
			.transaction(function(tx) {
				tx
						.executeSql(
								"select column_name from table_name LIMIT 1",
								[],
								function(tx) {
								},
								function(tx) {
									tx
											.executeSql('ALTER TABLE table_name ADD column_name  TEXT');
								});
			});

This above code working old version of Sqlite plugin but when i update Plugin to new one the above code not working please help me how to add new column to existing table in updated Sqlite plugin 

Thanks in advance.

**Comment by brody2consult** [comment]
@durgaprasadp can you try opening the database with `androidDatabaseImplementation: 2` as described in README.md and try it again?

**Comment by durgaprasadp** [comment]
Hi Bordybits ,

As per your suggestion i tried with below code but alter command not working below go thourght the code and suggest me .

Thanks in Advance



<script type="text/javascript">
		var dbObj
		function ConectionDb() {

			try {
				var Database_Name = 'temp.db';
						
				dbObj = window.sqlitePlugin.openDatabase({
					name : Database_Name,
					androidDatabaseImplementation : 2
				});
				

				dbObj
						.transaction(function(tx) {
							tx
									.executeSql('CREATE TABLE IF NOT EXISTS Conga_Applications (Application_ID , Application_Name, Application_Description,ProjectID,Partner_ID,User_ID,Role_ID,Created,IsActive,CreatedBy,ApplicationLogo,ApplicationLogo_base,IsMyFavourite,IsDownloaded,Quotes,FAQ,MoreAbout,WhyThisCourse,Instructor,InstructorLogo,IsPublish,InstructorID)');
						});

				dbObj
						.transaction(function(tx) {
							alert("course start select");
							tx
									.executeSql(
											"select course_start from Conga_Applications LIMIT 1",
											[],
											function(tx) {
											},
											function(tx) {
												alert("course start select fail and alter ");
												tx
														.executeSql('ALTER TABLE Conga_Applications ADD course_start TEXT');
												
												alert("course start select fail and after alter ");
											});
						});
			} catch (err) {
				alert(err.message + " at db connection ");
			}
			//alert(dbObj);

		}

		document.addEventListener("deviceready", ConectionDb, false);

		document.addEventListener("backbutton", logexit, false);

		function logexit() {
			navigator.app.exitApp();
		}
	</script>

**Comment by durgaprasadp** [comment]
Hi Bordybits ,

<script type="text/javascript">
		var dbObj
		function ConectionDb() {

			try {
				var Database_Name = 'temp.db';
						
				dbObj = window.sqlitePlugin.openDatabase({
					name : Database_Name,
					androidDatabaseImplementation : 2
				});
				

				dbObj
						.transaction(function(tx) {
							tx
									.executeSql('CREATE TABLE IF NOT EXISTS Conga_Applications (Application_ID , Application_Name, Application_Description,ProjectID,Partner_ID,User_ID,Role_ID,Created,IsActive,CreatedBy,ApplicationLogo,ApplicationLogo_base,IsMyFavourite,IsDownloaded,Quotes,FAQ,MoreAbout,WhyThisCourse,Instructor,InstructorLogo,IsPublish,InstructorID)');
						});

				dbObj
						.transaction(function(tx) {
							alert("course start select");
							tx
									.executeSql(
											"select course_start from Conga_Applications LIMIT 1",
											[],
											function(tx) {
											},
											function(tx) {
												alert("course start select fail and alter ");
												tx
														.executeSql('ALTER TABLE Conga_Applications ADD course_start TEXT');
												
												alert("course start select fail and after alter ");
											});
						});
			} catch (err) {
				alert(err.message + " at db connection ");
			}
			//alert(dbObj);

		}

		document.addEventListener("deviceready", ConectionDb, false);

		document.addEventListener("backbutton", logexit, false);

		function logexit() {
			navigator.app.exitApp();
		}
	</script>
 
As per your suggestion i tried with below code but alter command not working please  go through the code and suggest me .

Thanks in Advance

**Comment by durgaprasadp** [comment]
<script type="text/javascript">
		var dbObj
		function ConectionDb() {

			try {
				var Database_Name = 'temp.db';
						
				dbObj = window.sqlitePlugin.openDatabase({
					name : Database_Name,
					androidDatabaseImplementation : 2
				});
				

				dbObj
						.transaction(function(tx) {
							tx
									.executeSql('CREATE TABLE IF NOT EXISTS Conga_Applications (Application_ID , Application_Name, Application_Description,ProjectID,Partner_ID,User_ID,Role_ID,Created,IsActive,CreatedBy,ApplicationLogo,ApplicationLogo_base,IsMyFavourite,IsDownloaded,Quotes,FAQ,MoreAbout,WhyThisCourse,Instructor,InstructorLogo,IsPublish,InstructorID)');
						});

				dbObj
						.transaction(function(tx) {
							alert("course start select");
							tx
									.executeSql(
											"select course_start from Conga_Applications LIMIT 1",
											[],
											function(tx) {
											},
											function(tx) {
												alert("course start select fail and alter ");
												tx
														.executeSql('ALTER TABLE Conga_Applications ADD course_start TEXT');
												
												alert("course start select fail and after alter ");
											});
						});
			} catch (err) {
				alert(err.message + " at db connection ");
			}
			//alert(dbObj);

		}

		document.addEventListener("deviceready", ConectionDb, false);

		document.addEventListener("backbutton", logexit, false);

		function logexit() {
			navigator.app.exitApp();
		}
	</script>
