### ISSUE TITLE
Database isn't closed on Android devices

### ISSUE THREAD

**Issue by MacMario** [brodysoft/Cordova-SQLitePlugin#153]
Hi there!

I expericenced problems when closing the SQLite Database on Android devices after each statement executed (this is necessary in my case to enable other components to connect to the DB). 

I figured out that the database is removed from the dbrmap (SQLitePlugin.java @ Line 802) before it is tried to be closed @ Line 804. 

Therefore the DB is not closed (mydb is null @ Line 277), but no error is raised. On Android devices, I received "A SQLiteConnection object for database was leaked!" errors after some Sqlite calls. 

Swapping the two lines 802 and 804 resolves this issue.

**Comment by brodybits** [comment]
Same issue and same solution were already given in #150.

**Comment by brodybits** [comment]
The fix is now published (see #150).
