### ISSUE TITLE
Where to place de DB File in Android Project

### ISSUE THREAD

**Issue by ro-puente** [brodysoft/Cordova-SQLitePlugin#163]
Hey there, this might be a n00b question, but where do I need to place my db file in an android project?

Right now I've tried placing it inside the platforms/android/assets folder, in the same level as the www folder in my ionic project.

**Comment by brodybits** [comment]
Duplicate of #10, moving discussion to #172.

**Comment by brodybits** [comment]
I have now pushed a new release to master with optional support for pre-populated database. Please see README.md for details.
