### ISSUE TITLE
Project support level

### ISSUE THREAD

**Issue by confile** [brodysoft/Cordova-SQLitePlugin#165]
It seems that this project is not supported anymore?

**Comment by assetsense** [comment]
What happened to @brodybits ? This plugin seems to be a cool one. Is it really being discontinued?

**Comment by confile** [comment]
+1

**Comment by brodybits** [comment]
Guys my apologies. I had been preocupied with some business problems.

-10

I will go through the questions and reported issues over the coming few
weeks.

Unfortunately I will be running this project in a maintenance mode, i.e. no
new features for the next few months. I have to deal with some serious
business problems and cannot promise anything until I get them sorted out.

Chris @brodybits

On Wednesday, January 14, 2015, Confile <notifications@github.com> wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/165#issuecomment-69875334>
> .
>


-- 
Sent from my mobile
