### ISSUE TITLE
Open Existing SQLite DB file (pre-population)

### ISSUE THREAD

**Issue by gtjr92** [brodysoft/Cordova-SQLitePlugin#172]
I am trying to open an existing sqllite database. I can't seem to get it to open. 
I have copied the db file to the platforms/android/assets directory. I don't get any errors in the output. 
I am using ionic framework
here is my code
   
         <script src="lib/ionic/js/ionic.bundle.js"></script>
         <script src="js/ng-cordova.min.js"></script>
      <script src="cordova.js"></script>
	  <script>
var db =null;
	  function onDeviceReady() {
  db = sqlitePlugin.openDatabase({name: "testdb"});
   db.transaction(function(tx) {
        tx.executeSql("SELECT * FROM people limit 20;",[], function() {
             var testTable = new htTable();
                        testTable.setHeader(['name', 'address', 'phone']);
                      for( var i = 0; i < r.rows.length; i++ ) {
                            var row = r.rows.item(i);
                            testTable.addRow([row.city, row.state, row.zipcode]);
                        }
                       element('data').innerHTML = testTable.getTableHTML();
                      
        });

    }, function(e) {
      console.log("ERROR: " + e.message);
    });
    }
	</script>
</head>

<body>
<div id="data">
    
    DB TEST
    </div>
</body>

**Comment by brodybits** [comment]
This is pre-population, which others have been asking for. See #10 for old discussions.

**Comment by brodybits** [comment]
There are some old forks that have implemented pre-population. Solutions have been given over the net, and also on the forum. I am now considering integrating (Android and iOS only), under an *optional* parameter.

**Comment by brodybits** [comment]
I have now pushed a new release to master with optional support for pre-populated database. Please see README.md for details.

**Comment by taaa22** [comment]
If you still interested please look at this solution:
https://github.com/taaa22/Ionic-Sqlite
