### ISSUE TITLE
Cordova+iOS Maximum data storage limitation?

### ISSUE THREAD

**Issue by gooodguy** [brodysoft/Cordova-SQLitePlugin#174]
Hi,

first of all, thank you for this amazing project.
I am using the project in a cordova/pouchdb app and I want to deploy it on iPads.

I want to replicate a larger couchdb (32MB compressed, 60 MB uncompressed) so that it is available locally on the device. However, the replication fails at some point, after 4000 written docs and 87 MB of data. The total size of the app is 170 MB (87MB data + 83 MB webapp). I set the bulk size to 25 documents.

On one of my test devices, an iPad Air (iOS 7.1.1.), the following error is printed when the replication fails:
```PouchError
line: 6265
message: "there was not enough remaining storage space, or the storage quota was reached and the user declined…"
name: "Object"
result: Object
sourceURL: "file:///var/mobile/Applications/.../www/app/bowe…"
stack: "file:///var/mobile/Applications/.../www/app/bowe…"
__proto__: —
```

I got it working on a second iPad after two replication attempts. However, the performance is very slow. Much slower than using couchdb directly. 

My questions are:
* Is there any limit of the maximum storage size using the sqlite plugin on ios?
* Does anyone has experience with databases of that size on ios?
* What might cause the poor performance? What can I do to optimize the performance?

**Comment by nolanlawson** [comment]
I'm not aware of a maximum limit for the SQLite plugin; maybe your iPad Air really ran out of space? If you're worried about taking up too much space, you can use something like [filter-pouch](https://github.com/nolanlawson/filter-pouch) to store smaller versions of the same documents.

As for replication performance, it is most likely a PouchDB issue. Currently the best solution is to use [pouchdb-dump and pouchdb-load](https://github.com/nolanlawson/pouchdb-load) for quicker initial replication, and then switch over to normal replication after that.

**Comment by gooodguy** [comment]
The settings of the iPad Air tells me that there are still 10 GB available, so that should not be the problem.
Compression is not really an option in long-sight, because the database might be even larger than 60MB.
I will try pouchdb-dump and pouchdb-load. 
Another idea was to create a sqlite file and ship this file directly with the app (althrough this is not really an option in long-sight). But how can I create such a sqlite file?

BTW: I also updated the iPad Air to iOS 8.1.2 without any improvements.

**Comment by gooodguy** [comment]
I've found a solution by myself. For those, who are interessted:
* I've reduced the app-size by removing unnessary modules of an JS-framework I use (Dojo). The additional free space can then be used for the database and replication succeeds. I think that implies that there is some kind of limitation on iOS.
* Concerning the bad performance: I simply removed some unneccessary include_docs: true flags from some view queries.

**Comment by brodybits** [comment]
Happy to hear that you found a solution. Maybe should be added to a "Tips and tricks" section.

**Comment by gooodguy** [comment]
I analysed this problem in more detail. I created a little script that inserts random data into the database on my ipad. However, the script stops after approx. 100MB with no error message. When I run second time, again 100MB are inserted. I repeated this procedure and at the moment, the app consumes 1,1 GB. Does anyone have an idea why the script stops after 100MB?

 ```javascript
            function log(message){

                var console = document.getElementById("console");
                console.innerHTML += message+"</br>";
            }

            function generateData(length){
                var text = "";
                var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

                for( var i=0; i < length; i++ ){
                    text += possible.charAt(Math.floor(Math.random() * possible.length));
                }

                return text;
            }

            function callback2(){

                counter++;

                counterDom.innerHTML = counter;

                sizeDom.innerHTML = counter*100;

                if(counter<20000 && running){
                    return db.post(data).then(callback2);
                }
                else{
                    log("DONE!");
                    //throw new Error("DONE!");
                    return;
                }

            }

            document.addEventListener("deviceready", onDeviceReady, false);

            var running = true;
            var counter = 0;
            var Promise = PouchDB.utils.Promise;
            var db = null;
            var counterDom = document.getElementById("docCount");
            var sizeDom = document.getElementById("size");
            var data = {};
            data["data"] = generateData(104500);
            //onDeviceReady();
            function onDeviceReady() {

                db = new PouchDB("test",{adapter:'websql'});
                db.post(data).then(callback2);

            }
```

**Comment by gooodguy** [comment]
After reducing the size of the random string I get the same error after 1000 transactions. So I think it is a duplicate of https://github.com/brodysoft/Cordova-SQLitePlugin/issues/190

**Comment by brodybits** [comment]
In #190, @erikvorkink mentioned a possible workaround to change the Javascript native bridge mode to XHR as described here: https://github.com/apache/cordova-ios/blob/master/guides/Changing%20the%20JavaScript%20to%20Native%20Bridge%20Mode.md

Can you try it and report whether or not it solves the problem?

**Comment by gooodguy** [comment]
yes. solved. thanks.

**Comment by kievsash** [comment]
About changing NativeBridgeMode:
As I see now cordova.exec object doesn't have setJsToNativeBridgeMode method (and jsToNativeModes collectio as well) (checked it on deviceready event). Correct me if I'm wrong. Did cordova deprecate this method? 
Wanted to try it out cause our cordova application experience our of memory issue while working with sqlite on IPad devices with  1Gb of memory (IPad mini). Ipad Pro (4Gb of Ram) is doing well by the way
