### ISSUE TITLE
Performance impact on UI (Windows Phone)

### ISSUE THREAD

**Issue by vilic** [brodysoft/Cordova-SQLitePlugin#176]
Hi, thanks for this great plugin.

I am using this plugin for my project running on several platforms, it works great on Android, but for Windows Phone, it has obvious impact on UI.

The case is, when a user starts dragging some UI element, it will save a timestamp to database. But this operation (saving to database) blocks the UI for nearly a second (two "insert or replace" queries, separately).

Hope this makes sense to you guys.

**Comment by brodybits** [comment]
First, a general comment that using an ACID database (absolutely
failure-safe) even sqlite to keep track of _dragging_ may be overkill,
though great testimony for this project if it is working ok.

Please make sure you are using a recent version of the plugin. Some changes
were contributed in 2014 to handle the database in its own thread. Before
that the database queries had been blocking the UI thread.

Unfortunately I am not a WP(8) expert. Someone else made the WP(8) version
and I have integrated it with the same Javascript that works with the
other versions, with significant help from others.

If you see this issue with a recent version of the plugin, I suggest you
consider making and posting a small, self-contained test program that can
demonstrate the issue.

Chris

On Tuesday, January 20, 2015, VILIC VANE <notifications@github.com> wrote:

> Hi, thanks for this great plugin.
>
> I am using this plugin for my project running on several platforms, it
> works great on Android, but for Windows Phone, it has obvious impact on UI.
>
> The case is, when a user starts dragging some UI element, it will save a
> timestamp to database. But this operation (saving to database) blocks the
> UI for nearly a second (two "insert or replace" query, separately).
>
> Hope this makes sense to you guys.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brodysoft/Cordova-SQLitePlugin/issues/176>.
>


-- 
Sent from my mobile

**Comment by vilic** [comment]
Thanks, turns out to be the promise library with longStackTrace turned on is behind this issue.

**Comment by brodybits** [comment]
Thanks, turns out to be the promise library with longStackTrace turned on
is behind this issue.

Happy to hear it is ok!
