### ISSUE TITLE
SELECT query causes Cordova to throw `[NSNull length]: unrecognized selector` iOS

### ISSUE THREAD

**Issue by mirko77** [brodysoft/Cordova-SQLitePlugin#177]
I have been experiencing a weird issue when running a SELECT query on iOS (7 & 8)

my code:

    var _getOneHierarchyMediaFileTX = function(tx) {

			var query = "SELECT _id, value, type FROM ec_data WHERE form_id IN (SELECT _id FROM ec_forms WHERE project_id=? AND has_media=?) AND type=? AND is_data_synced=? AND is_media_synced=? AND value<>? LIMIT 1";

			tx.executeSql(query, [project_id, 1, media_type, 1, 0, ""], _getOneHierarchyMediaFileSQLSuccess, EC.Select.txErrorCB);
		};

which is pretty standard.

The app crashes with xCode logging:

`-[NSNull length]: unrecognized selector sent to instance 
*** Terminating app due to uncaught exception`

I tracked it back to Cordova.js failing on this function:

    function createExecIframe(src, unloadListener) {
        var iframe = document.createElement("iframe");
        iframe.style.display = 'none';
        // Both the unload listener and the src must be set before adding the iframe
        // to the document in order to avoid race conditions. Callbacks from native
        // can happen within the appendChild() call!
        iframe.onunload = unloadListener;
        iframe.src = src;
        document.body.appendChild(iframe);
        return iframe;
    }

exactly on this line:

` document.body.appendChild(iframe);`

Any suggestion? Works fine on Android

**Comment by mirko77** [comment]
I found the problem ;)

**Comment by brodybits** [comment]
> I found the problem ;)

Happy to hear !)
