### ISSUE TITLE
PhoneGap Build latest version

### ISSUE THREAD

**Issue by bayhall-digital** [brodysoft/Cordova-SQLitePlugin#180]
Is 1.0.3 available through PhoneGap Build or the Plugin Registry with the multipage Android update?

I'm experiencing intermittent trouble with Android KitKat 4.4.2 opening and not reading from the database.

**Comment by brodybits** [comment]
Nope, and there are a few other issues that I want to get fixed before
submitting to PhoneGap build.

Chris

**Comment by bayhall-digital** [comment]
Many thanks. Do you have a guesstimate for PhoneGap Build? 

Also - there seem to be many copies for this SQLitePlugin - for example com.triarc.sqliteplugin which looks to be version 1.0.3? They don't explain their differences.

**Comment by brodybits** [comment]
On Feb 4, 2015 9:25 PM, "bayhall-digital" <notifications@github.com> wrote:
>
> Many thanks. Do you have a guesstimate for PhoneGap Build?

Unfortunately not. I am dealing with some business issues right now so I
cannot make any real promise.

> Also - there seem to be many copies for this SQLitePlugin - for example
com.triarc.sqliteplugin which looks to be version 1.0.3? They don't explain
their differences.

Sounds like someone else decided to submit a version with the updates from
1.0.3. You can use it but in general the clone forks do not keep up to date.

**Comment by brodybits** [comment]
I have integrated changes to support pre-populated database (ref: #10/#172) and disable iCloud backup (ref: #16/#143) and will submit to PhoneGap within the next 1-2 weeks if no major issues are reported.

**Comment by brodybits** [comment]
1.0.4 has recently been published to PhoneGap Build, and I plan to publish the current release (1.0.5) soon.
