### ISSUE TITLE
Application did not close the cursor or database object that was opened here

### ISSUE THREAD

**Issue by ergovia-mobile** [brodysoft/Cordova-SQLitePlugin#182]
While debugging our app with `android monitor`, we came across an Exception that was thrown when processing lots of data.

`02-06 15:20:33.911: W/SQLiteCompiledSql(3765): net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here`

Do you have an idea, what causes the app to not close the database object ?

**Comment by brodybits** [comment]
SQLCipher will be supported in a new project.
