### ISSUE TITLE
Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by ergovia-mobile** [brodysoft/Cordova-SQLitePlugin#183]
Hi, we're getting this error sometimes on Android Devices possibly while opening the database. The cause remains unclear to us. Does anyone have an idea? We are using Cordova-SQLitePlugin
 with the SQLCipher.

`Attempt to invoke virtual method 'net.sqlcipher.database.SQLiteStatement net.sqlcipher.database.SQLiteDatabase.compileStatement(java.lang.String)' on a null object reference`

**Comment by brodybits** [comment]
SQLCipher will be supported in a new project.

**Comment by brodybits** [comment]
For those who are interested, I am happy to announce that I have just published a new version that supports SQLCipher embedded out-of-the-box here: https://github.com/brodysoft/Cordova-sqlcipher-adaptor

I hope that people will dare to try it out on both Android & iOS platforms. SQLCipher v3.2.0, which is currently the most recent release, is embedded as source code for iOS and as library code for
Android.

It is possible and recommended to install the sqlcipher version of the plugin using either the plugman tool or Cordova CLI.

In addition, there is (somewhat limited) automatic testing of the encryption & decryption functionality.
