### ISSUE TITLE
Opening same db sometimes fails on iOS

### ISSUE THREAD

**Issue by craig-at-rsg** [brodysoft/Cordova-SQLitePlugin#185]
I have multiple databases in my application, and I have some synchronous calls that open a database and select data. On iOS, this is sometimes not working... 

Here are the symptoms on iOS:
Opening a db and trying to open it again soon after sometimes returns an open db for both calls, and sometimes it returns an open db for the first call and never for the second - it looks like the callbacks aren't triggered in the error case. If you assume it will open and try to select from it, you get the error message "No such database, you must open it first".

I do get the message that SQLite is thread safe. 

I'm using Cordova 3.6 against iOS 8.1 with this plugin's version r2014.07.

I could try keeping track of my open databases and reuse them, but I think this plugin is already doing that.

Any advice for me?

**Comment by brodybits** [comment]
Sounds like a timing issue. A lot of work had been done to solve this kind of issue on Android and WP(8) versions, and test cases (which also work OK on iOS) were added to reproduce the issues and verify the fix.

The workaround is to simply keep your open db object.

A test case that can reproduce the issue would be very helpful.

**Comment by craig-at-rsg** [comment]
Thanks for responding. Is there a particular version I need?

This seems very reproducible to me - it happens much more frequently than I would expect for a timing issue, so I can try making a test case if there isn't already a fix for this - I am on a tagged release from last summer.

**Comment by brodybits** [comment]
It would help if you can upgrade to the latest version. Some changes were made which _may_ have an effect in your case. Also there is a test case of repeatedly opening and closing a database, which *does* pass OK (in the newer versions).

**Comment by craig-at-rsg** [comment]
I tried the latest, and the opens seem to work now in iOS, thank you!
