### ISSUE TITLE
Can't get callback after select, stuck at executeSql - Android 4.1.1

### ISSUE THREAD

**Issue by nicolasds** [brodysoft/Cordova-SQLitePlugin#198]
I have a working project that works on an emulator with target android 4.4.2.

When i try to run the project on my real device, an acer tablet with android 4.1.1 i can't get the callback after the select statement, or any callback at all.

Tried with the test code in the main page. Database opens but the callbacks are not called.

What could be the problem? Thanks

**Comment by brodybits** [comment]
Not enough information. Can you post the trace from `adb logcat`?

**Comment by nicolasds** [comment]
Did a test with a simple page calling the plugin and it did work, sorry! My app uses angular, it has to be something with that. not the plugin.

This is the trace after the DeviceReady event, can you spot something suspicious?

03-06 11:37:20.444    2995-2995/com.silvicultura.android I/Web Console﹕ DEVICE READY! at file:///android_asset/www/views/shared/layout.html:108
03-06 11:37:20.514    2995-2995/com.silvicultura.android D/CordovaActivity﹕ Resuming the App
03-06 11:37:21.344    2995-2995/com.silvicultura.android D/CordovaActivity﹕ onMessage(spinner,stop)
03-06 11:37:21.344    2995-2995/com.silvicultura.android D/TilesManager﹕ new EGLContext from framework: 6793f4c8
03-06 11:37:21.344    2995-2995/com.silvicultura.android D/GLWebViewState﹕ Reinit shader
03-06 11:37:21.364    2995-2995/com.silvicultura.android D/GLWebViewState﹕ Reinit transferQueue
03-06 11:37:21.644    2995-2995/com.silvicultura.android D/CordovaLog﹕ file:///android_asset/www/services/dataBaseServiceAndroid.js: Line 11 : antes db
03-06 11:37:21.644    2995-2995/com.silvicultura.android I/Web Console﹕ antes db at file:///android_asset/www/services/dataBaseServiceAndroid.js:11
03-06 11:37:21.654    2995-2995/com.silvicultura.android D/CordovaLog﹕ file:///android_asset/www/plugins/com.brodysoft.sqlitePlugin/www/SQLitePlugin.js: Line 39 : SQLitePlugin openargs: {"name":"baseNueva5","dblocation":"docs"}
03-06 11:37:21.654    2995-2995/com.silvicultura.android I/Web Console﹕ SQLitePlugin openargs: {"name":"baseNueva5","dblocation":"docs"} at file:///android_asset/www/plugins/com.brodysoft.sqlitePlugin/www/SQLitePlugin.js:39
03-06 11:37:21.654    2995-2995/com.silvicultura.android D/CordovaBridge﹕ Ignoring exec() from previous page load.
03-06 11:37:21.664    2995-2995/com.silvicultura.android D/CordovaLog﹕ file:///android_asset/www/services/dataBaseServiceAndroid.js: Line 13 : desp db
03-06 11:37:21.664    2995-2995/com.silvicultura.android I/Web Console﹕ desp db at file:///android_asset/www/services/dataBaseServiceAndroid.js:13
03-06 11:37:21.664    2995-2995/com.silvicultura.android D/CordovaLog﹕ file:///android_asset/www/services/dataBaseServiceAndroid.js: Line 15 : en transaction
03-06 11:37:21.664    2995-2995/com.silvicultura.android I/Web Console﹕ en transaction at file:///android_asset/www/services/dataBaseServiceAndroid.js:15
03-06 11:37:21.664    2995-2995/com.silvicultura.android D/CordovaLog﹕ file:///android_asset/www/services/dataBaseServiceAndroid.js: Line 19 : antes pragma
03-06 11:37:21.664    2995-2995/com.silvicultura.android I/Web Console﹕ antes pragma at file:///android_asset/www/services/dataBaseServiceAndroid.js:19
03-06 11:37:21.664    2995-2995/com.silvicultura.android D/CordovaLog﹕ file:///android_asset/www/services/dataBaseServiceAndroid.js: Line 25 : antes insert
03-06 11:37:21.664    2995-2995/com.silvicultura.android I/Web Console﹕ antes insert at file:///android_asset/www/services/dataBaseServiceAndroid.js:25
03-06 11:37:21.674    2995-2995/com.silvicultura.android D/CordovaBridge﹕ Ignoring exec() from previous page load.
03-06 11:37:50.394    2995-2995/com.silvicultura.android D/CordovaActivity﹕ Paused the application!
03-06 11:37:50.394    2995-2995/com.silvicultura.android D/CordovaWebView﹕ Handle the pause
03-06 11:37:50.484    2995-2995/com.silvicultura.android D/CordovaActivity﹕ Resuming the App

Thank you very much for your time!

**Comment by nicolasds** [comment]
Tested on another device with android 4.1.1 and worked fine. Must be a device problem.

Thank you very much!
