### ISSUE TITLE
How to use new location option with pouchdb?

### ISSUE THREAD

**Issue by tannerlinsley** [brodysoft/Cordova-SQLitePlugin#200]
I'm confused how I can tell pouchdb to use the new location parameter to not back up to icloud.  Any ideas?

**Comment by nolanlawson** [comment]
You cannot. We haven't implemented it in PouchDB yet.

If you would like to contribute the fix to PouchDB, you are more than welcome to modify the code and submit a pull request. [Here is the code that will need to be modified](https://github.com/pouchdb/pouchdb/blob/a4ce4c68654e0059a10be11840b84c796f3d63b2/lib/adapters/websql/websql-utils.js#L179-L194). I would recommend adding an option to the PouchDB constructor, e.g. `sqlite_plugin_location` or something like that, and then passing it in to that `openDB` function.

**Comment by brodybits** [comment]
Thanks @tannerlinsley and @nolanlawson!

**Comment by brodybits** [comment]
In a more general case, it would be nice to configure default values as well. Nice to do this from `config.xml`, see: http://stackoverflow.com/questions/24939920/access-config-xml-preferences-from-javascript-plugins

**Comment by nolanlawson** [comment]
That's a nice pattern; thanks for sharing. :)

**Comment by tannerlinsley** [comment]
Using the above changes, my app says that it's opening a db, but nothing ever happens after this...

```
SQLitePlugin openargs: {"name":"","version":1,"description":"_pouch_myapp","size":1,"location":2,"dblocation":"nosync"}
```

**Comment by brodybits** [comment]
What you quote from the trace indicates that for some reason, the plugin attempts to open a database with name of "", which will not work. The plugin should check for and reject (probably with an exception) this case. Please try further to log or otherwise debug the "config" object given to sqlitePlugin.openDatabase.

**Comment by tannerlinsley** [comment]
False alarm.  I found a bug on my end.  Thanks for the help on this one guys!

**Comment by brodybits** [comment]
Happy to hear @tannerlinsley. I have raised #207 to add the XML enhancements whenever I get a chance (or someone else issues a pull request). And thanks to both @nolanlawson and @tannerlinsley for fixing PouchDB to work with the new `location` option.

**Comment by nolanlawson** [comment]
This feature should appear in the next release of PouchDB. Or for those who are in a hurry, here are some prerelease builds: [pouchdb.js](https://nolanlawson.s3.amazonaws.com/pouchdb/www/20150315/pouchdb.js) and [pouchdb.min.js](https://nolanlawson.s3.amazonaws.com/pouchdb/www/20150315/pouchdb.min.js).

**Comment by tannerlinsley** [comment]
Thanks!

**Comment by brody2consult** [comment]
FYI documented at: http://pouchdb.com/api.html#create_database

_(Link will be added to README.md when I get a chance.)_
