### ISSUE TITLE
ios safari debugger hangs in most times

### ISSUE THREAD

**Issue by flyingsky** [brodysoft/Cordova-SQLitePlugin#206]
It's very easy to reproduce, after do any query, the safari debugger is hanging and app is dead. You can use safari to remote debug ios simulator or ios device.

**Comment by nolanlawson** [comment]
I've found that the Safari debugger will often crash if you use an older version of Safari with a newer version of iOS. Are you running the latest Safari 8 on Yosemite?

**Comment by brodybits** [comment]
Thanks @nolanlawson for your input. Does not look like a bug with this project.

**Comment by flyingsky** [comment]
yes, latest safari 8 on yosemite. it works well for other phonegap plugins. so it's wired.

**Comment by flyingsky** [comment]
Why close it? Actually it still hangs and crash any time from my side. Nobody has similar issue on xcode and safari when you debug?

My environment is mac 10.10.3, xcode 6.3.1, safari 8.0.6.

Because the sqlite plugin cannot debug on ios, I'm frustrated about the sqlite plugin. Even I don't think phonegap is a good solution for any mobile development.

**Comment by brody2consult** [comment]
Is this a problem specifically this project? Looks like a phonegap or xcode
problem to me.

**Comment by flyingsky** [comment]
I don't think it's phonegap or xcode issue, because it works well without sqlite plugin. It seems sqlite plugin cause this issue.

**Comment by Cadey** [comment]
I have this exact same issue, whenever I put a break point on a promises win or fail the debugger crashes. It appears as if the debugger is stuck in paused mode and unable to come out.

**Comment by Cadey** [comment]
sorry, this was a more general iOS emulator  + cordova + safari remote inspector problem but just incase anyone knows what it is :)

**Comment by flyingsky** [comment]
I'm not sure if it's a general issue, because I never see it for other cordova plugin, just this plugin.
