### ISSUE TITLE
Using Lawnchair gives error : unexpected identifier

### ISSUE THREAD

**Issue by rinnungirenthlei** [brodysoft/Cordova-SQLitePlugin#216]
I tested the plugin and queries are working fine. But when i decided to use Lawnchair it did not went well.

I added the required js files in index.html :
<script type="text/javascript" src="js/lawnchair.js"></script>
<script type="text/javascript" src="js/SQLitePlugin.js"></script>
<script type="text/javascript" src="js/Lawnchair-sqlitePlugin.js"></script>

and when i call this :
var db_name = new Lawnchair {name: "db_name", function(){}};

it throws error :
Uncaught SyntaxError: Unexpected identifier.

Am i missing something here ?
Quick reply will be appreciated.
Regards.

**Comment by rinnungirenthlei** [comment]
Also how to do query with Lawnchair like "SELECT * WHERE id IN(myids);" ? 
Friends, an example of lawnchair with this plugin would be great,
Regards.

**Comment by brodybits** [comment]
Looks like you answered your own questions in #217.

**Comment by brodybits** [comment]
The cause of this issue was improper documentation. The Lawnchair examples should be given in Javascript to avoid the confusion.

**Comment by rinnungirenthlei** [comment]
Thank you brodybits, Yes it was due to weak documentation. Please update it for new users to avoid confusion.
