### ISSUE TITLE
SQLitePlugin opening database twice

### ISSUE THREAD

**Issue by rinnungirenthlei** [brodysoft/Cordova-SQLitePlugin#217]
Hi friends,
I called this arg in the begginning and i see in console that it triggered the database opening function :
var db = window.sqlitePlugin.openDatabase({name: "test.db", androidLockWorkaround: 1});

Then after that when i call this function it again call the database opening function :
var dbusers = new Lawnchair({db: "test", name: "user"}, function(){});

Is it opening/creating two different database / data ? 
I guess this is an issue.

Waiting for a reply,
Regards.

**Comment by brodybits** [comment]
I think you need the full database file name when asking for the new Lawnchair as well. Needs to be documented. Also, the Lawnchair examples should be converted to Javascript.

**Comment by rinnungirenthlei** [comment]
Hi Brodybits,
Thank you for replying,
I replaced the database name "test" with full name "test.db" but still no positive result. The database opening is triggered twice. Is this because the first opening has "androidLockWorkaround" parameter ?

**Comment by brodybits** [comment]
There are two db handle objects in the Javascript, but they *should* access the same database file! If you need the Android lock workaround, make sure you open the database by calling `sqlitePlugin.openDatabase()` before starting the Lawnchair.

Unfortunately, I have not updated the Lawnchair adapter for a few years. Also, to make it work with the pre-populated database or access the database in a different location you would have to call `sqlitePlugin.openDatabase()` first.

**Comment by brodybits** [comment]
Lawnchair examples are now converted to Javascript, and a note with the workaround is added. I raised #219 to fix the Lawnchair adapter to handle the new db options, sometime when I get a chance.
