### ISSUE TITLE
[help] how to save data from json

### ISSUE THREAD

**Issue by marti1125** [brodysoft/Cordova-SQLitePlugin#218]
I have this json http://env-2953640.jelastic.lunacloud.com/RestMaquinaria/rest/RestService/listaStocks
how to I can save data? using $.getJSON and $.each =?

**Comment by brodybits** [comment]
Supporting HTTP/JSON/JQuery is beyond the scope of this project but I will try to help. Yes you can use $.getJSON to get the data. I looked at your JSON and it looks like only one record, in which case I would recommend something like:
```Javascript
$.getJSON("your.path.to.json", function(data) {
  db.executeSql("INSERT into your_table (id, price, equipment, city) VALUES (?,?,?,?)",
    [data.id, data.precio, data.maquinaria, data.municipalidad]);
});
```

If your service would return a JSON *array* of objects, then it would make sense to use $.each (ref: https://api.jquery.com/jquery.each/):

```Javascript
$.getJSON("your.path.to.json", function(data) {
  db.transaction(function(tx) {
    $.each(data, function(index, val) {
      tx.executeSql("INSERT into your_table (id, price, equipment, city) VALUES (?,?,?,?)",
        [val.id, val.precio, val.maquinaria, val.municipalidad]);
    )};
  });
});
```

Hope I didn't make any mistakes!

**Comment by marti1125** [comment]
Thanks :+1:

**Comment by brodybits** [comment]
De nada
