### ISSUE TITLE
SQLite PLugin Error: no such function: if (code 1)

### ISSUE THREAD

**Issue by rinnungirenthlei** [brodysoft/Cordova-SQLitePlugin#220]
Hi Brodybits,
I want to use this query with SQLite for my chat section :
select PreQuery.*, m2.message, m2.ufrom, m2.uto from ( SELECT  if( m.ufrom < m.uto, m.ufrom, m.uto ) as Person1, if( m.ufrom < m.uto, m.uto, m.ufrom ) as Person2, max( m.chatid ) as LastMessageIDPerChat, max( m.sent ) as LastMessageDate FROM chat m GROUP BY Person1, Person2 ORDER BY m.sent DESC LIMIT 50 ) PreQuery JOIN chat m2 on PreQuery.LastMessageIDPerChat = m2.chatid

No issue with the query. The error says that there is no function "if" in the Plugin.
What will be the solution for this ? How can i add the function in SQLitePlugin.js ?
Thanks for listening my earlier issues.
Regards.

**Comment by brodybits** [comment]
SQLite uses CASE/WHEN instead of IF: http://www.sqlite.org/lang_expr.html#case

Other links:
- http://stackoverflow.com/questions/14580294/sqlite-syntax-for-if-else-condition
- http://stackoverflow.com/questions/1294619/does-sqlite-support-any-kind-of-ifcondition-statement-in-a-select

**Comment by rinnungirenthlei** [comment]
Ohh Okay. Thank you so much Brodybits :)
