### ISSUE TITLE
RikshaDriver ios plugin build is failing in XCode

### ISSUE THREAD

**Issue by siddo420** [brodysoft/Cordova-SQLitePlugin#56]
I get the following error on XCode Version 5.1.1.

```
Use of undeclared identifier 'dbfile'
```
in SQLitePlugin.m on the statement inside the if block below:
```
           //Check if Database Exists and Copy
            if (![[NSFileManager defaultManager] fileExistsAtPath:dbname]) {
            	[self copyPrepopulatedDatabase:dbfile withDbname:dbname];
            }
```

This is happening with RikshaDriver plugin only and not the original one. There is no issues page on RikshaDriver repository itself. And, the plugin works fine on Android.

Please let me know how to fix it and/or fix it and upload for testing.

Thanks.

**Comment by timothyha** [comment]
https://github.com/Antair/Cordova-SQLitePlugin - @brodybits, Chris, this one doesn't build, too

```
......./com.phonegap.plugins.sqlite/SQLitePlugin.m:211:45: error: use of undeclared identifier 'dbfile'
                [self copyPrepopulatedDatabase:dbfile withDbname:dbname];
                                               ^
1 error generated.
```

**Comment by brodybits** [comment]
Pre-populated database support is now integrated.
